name: Build ZMK firmware
on: workflow_dispatch

jobs:
  defaults:
    revision: v0.3
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml
    with:
      build_matrix_path: 'central_left.yaml'
